import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { Geist, Geist_Mono } from 'next/font/google';
import { AppSidebar } from '@/components/common/App-sidebar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function BoardLayout({ children }) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className='w-full'>
        <SidebarTrigger />
        {children}
      </main>
    </SidebarProvider>
  );
}
